### ISSUE TITLE
Add "two clicks for more privacy" on the like button

### ISSUE THREAD

**Issue by hargup** [metakgp/mfqp#15]
Using this (http://panzi.github.io/SocialSharePrivacy/) scrip will prevent tracking by Facebook through our page.

**Comment by icyflame** [comment]
@hargup Although this is a good idea, I don't think that with something like that, anyone will have any idea what to do. And this will only reduce the people who come to our page. I don't think that we should do this.

**Comment by hargup** [comment]
Well, that's what we are doing, giving users the right default as they aren't expected to know enough to protect themselves online (they can use something like [privacy badger](https://www.eff.org/privacybadger)).

**Comment by icyflame** [comment]
@hargup Thanks a lot for that extension, I have installed it. It might be a better idea to popularise that in KGP, instead of using a widget that no one will know how to use. :slightly_smiling_face: In the interest of privacy, we might make a page on the Metakgp wiki and share it from our Facebook page to increase the visibility of such extensions.

**Comment by DefCon-007** [comment]
We have also not featured any wiki page from a long time making a page for it and then featuring it will be nice.

**Comment by hargup** [comment]
I don't want to push this on a community project anymore.
