### ISSUE TITLE
Suggest mid sem papers first during mid sem and vice versa?

### ISSUE THREAD

**Issue by punit1108** [metakgp/mfqp#32]
This could be a tad bit helpful to the users.

**Comment by vivekiitkgp** [comment]
Very interesting idea. :+1:

**Comment by DefCon-007** [comment]
We can write a script that will read the json and place mid sem first or end sem first according to the month and then save the JSON. And then set a cron job to run during the exams

**Comment by athityakumar** [comment]
Or, we can also dynamically sort the json-read array of hashes in the `js` code itself, by putting a check on the current date. No cron job required then.

**Comment by DefCon-007** [comment]
@athityakumar But won't it increase the load time of search results ?

**Comment by athityakumar** [comment]
Just the initial loading, and not the subsequent searches. And the delay won't be too much hopefully. 

@icyflame - What's your opinion on this?

**Comment by AvijitGhosh82** [comment]
Instead of putting them first or last we could have midsem and endsem papers appearing under different divs with 'Midsem Papers' and 'Endsem Papers' as headers. This would not take any extra time and would look neater as well.

**Comment by amrav** [comment]
I'm not sure if this feature is an improvement. Personally, I'd rather have the search rank according to what I type, rather than some measure of what it thinks I want, especially if it could get it wrong. I don't mind typing an additional 4 characters for " mid" and get those on top.

If you do want to do this, it shouldn't be hard to modify the scoring formula to check the date and weigh midsem papers higher.

**Comment by icyflame** [comment]
I think we have determined that this is not something we want right now. @punit1108 Thanks for the suggestion anyway! :slightly_smiling_face:
