### ISSUE TITLE
Add shell script to automate the 3-commit procedure

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mfqp#37]
### JSON: Minified and pretty-printed

A JSON file can either be a minified one, or a pretty-printed one. The minified one takes lesser space and is advantageous to store in a git-based repository. However, the minified one is really awful when checking for `git diff`, as it's just one line of old string replaced by one line of new string. Rather, pretty-printed JSON has much better git diff. Hence, it's easy to review Pull Requests with JSON changes, based on pretty-printed JSON.

### The 3-commit procedure

Our remote master MUST always contain the minified JSON. When a contributor is adding a few papers, or trying to remove buggy ones in the JSON file, this is the commit procedure to follow -

Commit 1. Pretty-print the existing minified JSON
Commit 2. Change the pretty-printed JSON file as required
Commit 3. Minify the changed JSON file

This way, the minified file is stored at the end and someone reviewing the Pull Request will have to just see the diff between commits 1 and 2.

**Comment by icyflame** [comment]
No no, this is not what I want in the long term. It's a head ache. The code should be in master and it should be built properly to the appropriate form and pushed to gh-pages. Definitely don't want this. Sorry. :smile: I will probably work and close off #16 because of how inconvenient the present thing is. (Also, this interferes with the other _actual_ changes in the code)
